route:
  receiver: admin

receivers:
- name: admin
  email_configs:
  - to: 'jcroyoaun@gmail.com'
    from: 'alguien@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'example@gmail.com'
    auth_identity: 'example@gmail.com'
    auth_password: ''

receivers:
- name: admin
  email_configs:
  - to: 'example@gmail.com'
- name: slack-test
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    #title: 'WMI exporter is down'
    #text: WMI exporter is down for more than 2 minutes'
